---
# Basic provisioning example
#- local_action:
#    module: ec2
#    key_name: mykey
#    instance_type: c1.medium
#    image: emi-40603AD1
#    wait: yes
#    group: webserver
#    count: 3

# Must export the following environment variables:
#   AWS_ACCESS_KEY
#   AWS_SECRET_KEY

- name: Create instance(s)
  hosts: localhost
  gather_facts: False
  vars:
    key_name: mbro
    instance_type: m1.small
    security_group_id: sg-33f9ff56
    image: ami-22ed474a
    region: us-east-1
  tasks:
    - name: Launch instance
      local_action: ec2 key_name={{ key_name }} group_id={{ security_group_id }} instance_type={{ instance_type }} image={{ image }} wait=yes region={{ region }} count=1
      register: ec2

    - local_action: osx_say msg="Hosts are launched" voice=Zarvox
#    - local_action: osx_say msg="Hosts are launched" voice=Samantha
#    - local_action: osx_say msg="Hosts are launched" voice="Bad News"

    - name: Add new instance(s) to the 'launched' group so we can reference them later
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
#      local_action: add_host hostname=ec2-54-172-166-17.compute-1.amazonaws.com groupname=launched
      with_items: ec2.instances

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=5 timeout=320 state=started
#      local_action: wait_for host={{ item }} port=22 delay=5 timeout=320 state=started
      with_items: ec2.instances    
#      with_items: launched

- name: Setup mbrocious user account
  hosts: launched
  sudo: yes
  remote_user: ubuntu
  tasks:
    - name: Create the account
      user: name=mbrocious group=sudo shell=/bin/bash password=$6$rounds=100000$To1rEsfvbPqhOIUD$xuOSJVhb1V3yJ8YuQozIfHu818H5CI1rz0ymH7D4SIYgL0P/d/Kfmu8sFLoPY/E4e19WEwAyMmcE5wuzfupY0/
    - name: Set up authorized_keys for the user
      authorized_key: user=mbrocious key="{{ item }}"
      with_file:
        - /Users/mike/.ssh/id_rsa.pub



    # - name: Terminate instances that were previously launched
    #   local_action:
    #     module: ec2
    #     state: 'absent'
    #     region: us-east-1
    #     instance_ids: '{{ ec2.instance_ids }}'
    #     key_name: mbro2
